services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library-system
    ports:
      - '5000:5432'
    volumes:
      - db:/data/postgres
volumes:
  db: